version: 2
 
models:
    - name: dbt_demo1
      description: "A starter dbt model"
      columns:
          - name:  C_CUSTKEY
            description: "The primary key for this table"
            tests:
                - not_null_demo
                
         - name:  C_NAME
            description: "The primary key for this table"
            tests:
                - not_null_demo